import { NextRequest, NextResponse } from 'next/server';
import axios from 'axios';
import { load } from 'cheerio';

const cache = new Map<string, { data: any, timestamp: number }>();
const CACHE_TTL = 1000 * 60 * 10; // 10 minutes
const AI_GENERATED_PATTERN = /\b(ai[- ]generated|generative ai|generated by ai|midjourney|stable diffusion|dall[- ]?e)\b/i;

function isAiGeneratedStockResult(item: {
  title?: string;
  description?: string;
  tags?: string[];
}) {
  const searchableText = [
    item.title || '',
    item.description || '',
    ...(item.tags || []),
  ].join(' ');
  return AI_GENERATED_PATTERN.test(searchableText);
}

// Configure axios default timeout
const axiosInstance = axios.create({
  timeout: 10000, // 10 seconds timeout
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
  }
});

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const query = searchParams.get('q');
    const type = searchParams.get('type') || 'all';
    const era = searchParams.get('era') || '';
    const providers = searchParams.get('providers') || 'all';

    if (!query) {
      return NextResponse.json({ error: 'Query is required' }, { status: 400 });
    }

    const cacheKey = `${query}-${type}-${era}-${providers}`;
    const cached = cache.get(cacheKey);
    if (cached && (Date.now() - cached.timestamp < CACHE_TTL)) {
      return NextResponse.json({ results: cached.data, cached: true });
    }

    const providersToSearch = providers === 'stock'
      ? [searchPexels(query, type), searchPixabay(query, type)]
      : [
        searchInternetArchive(query, type),
        searchLOC(query, type, era),
        type !== 'video' ? searchSmithsonian(query, type, era) : Promise.resolve([]),
        searchPexels(query, type),
        searchPixabay(query, type),
        searchGoogle(query, type),
      ];
    const results = await Promise.allSettled(providersToSearch);

    const flatResults = results
      .filter((r) => r.status === 'fulfilled')
      .flatMap((r: any) => r.value || []);
    const visibleResults = providers === 'stock'
      ? flatResults.filter((item) => !isAiGeneratedStockResult(item))
      : flatResults;

    // Save to cache
    cache.set(cacheKey, { data: visibleResults, timestamp: Date.now() });

    return NextResponse.json({ results: visibleResults });
  } catch (error: any) {
    console.error('Search API Error:', error);
    return NextResponse.json({ 
      error: 'Search failed', 
      details: error.message 
    }, { status: 500 });
  }
}

async function searchSmithsonian(query: string, type: string, era: string) {
  const API_KEY = process.env.SMITHSONIAN_API_KEY || 'DEMO_KEY';
  const q = `${query} ${era}`.trim();
  const url = `https://api.si.edu/openaccess/api/v1.0/search?q=${encodeURIComponent(q)}&api_key=${API_KEY}&rows=50`;

  try {
    const response = await axiosInstance.get(url);
    const rows = response.data?.response?.rows || [];

    return rows.map((row: any) => {
      const content = row.content;
      const media = content?.descriptiveNonRepeating?.online_media?.media || [];
      const thumbnail = media[0]?.thumbnail || media[0]?.content || '';
      const downloadUrl = media[0]?.content || '';
      const year = content?.freetext?.date?.[0]?.content || row.year || '';

      return {
        id: row.id,
        source: 'Smithsonian',
        title: row.title || 'Untitled Smithsonian Asset',
        type: 'image', 
        year,
        thumbnail,
        description: content?.descriptiveNonRepeating?.metadata_usage?.text || '',
        downloads: 0,
        tags: content?.indexedStructured?.topic || [],
        downloadUrl,
      };
    }).filter((item: any) => item.thumbnail);
  } catch (err: any) {
    console.error('Smithsonian search failed:', err.message);
    return [];
  }
}

async function searchInternetArchive(query: string, type: string) {
  let mediatype = '(mediatype:movies OR mediatype:image)';
  if (type === 'video') mediatype = 'mediatype:movies';
  if (type === 'image') mediatype = 'mediatype:image';

  const searchableTerms = query
    .replace(/[^a-z0-9\s-]/gi, ' ')
    .trim()
    .split(/\s+/)
    .slice(0, 6)
    .join(' ');
  const fullQuery = `${mediatype} AND collection:prelinger AND (${searchableTerms || 'daily life'})`;
  const url = `https://archive.org/advancedsearch.php?q=${encodeURIComponent(fullQuery)}&fl[]=identifier,title,mediatype,year,description,subject,downloads&rows=50&output=json&sort[]=downloads+desc`;

  try {
    const response = await axiosInstance.get(url);
    const docs = response.data?.response?.docs || [];

    return docs.map((doc: any) => {
      const tags = [...(doc.subject || []), ...(doc.title?.split(' ') || [])].filter(t => t.length > 3).slice(0, 10);
      
      return {
        id: doc.identifier,
        source: 'Internet Archive',
        title: doc.title,
        type: doc.mediatype === 'movies' ? 'video' : 'image',
        thumbnail: `https://archive.org/services/img/${doc.identifier}`,
        url: `https://archive.org/details/${doc.identifier}`,
        year: doc.year || '',
        description: doc.description || '',
        downloads: doc.downloads || 0,
        tags: Array.from(new Set(tags)),
        downloadUrl: doc.mediatype === 'movies' 
          ? `https://archive.org/download/${doc.identifier}/${doc.identifier}.mp4` 
          : `https://archive.org/download/${doc.identifier}/${doc.identifier}.jpg`,
      };
    });
  } catch (err: any) {
    console.error('IA Search Error:', err.message);
    return [];
  }
}

async function searchLOC(query: string, type: string, era: string) {
  const fullQuery = `${query} ${era} vintage`;
  const fa = type === 'image' ? 'online-format:image' : type === 'video' ? 'online-format:video' : '';
  const url = `https://www.loc.gov/photos/?q=${encodeURIComponent(fullQuery)}&fo=json&c=50${fa ? `&fa=${encodeURIComponent(fa)}` : ''}`;

  try {
    const response = await axiosInstance.get(url);
    const results = response.data?.results || [];

    return results.map((item: any) => ({
      id: item.id,
      source: 'Library of Congress',
      title: item.title,
      type: (item.original_format && item.original_format[0]?.includes('video')) ? 'video' : 'image',
      thumbnail: item.image_url ? item.image_url[item.image_url.length - 1] : '',
      url: item.url,
      year: item.date || '',
      description: item.description ? item.description[0] : '',
      downloadUrl: item.image_url ? item.image_url[item.image_url.length - 1] : '',
    }));
  } catch (err: any) {
    console.error('LOC Search Error:', err.message);
    return [];
  }
}

async function searchPexels(query: string, type: string) {
  const API_KEY = process.env.PEXELS_API_KEY;
  if (API_KEY) {
    try {
      if (type === 'all') {
        const [photoRes, videoRes] = await Promise.allSettled([
          axiosInstance.get(`https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=8`, { headers: { Authorization: API_KEY } }),
          axiosInstance.get(`https://api.pexels.com/v1/videos/search?query=${encodeURIComponent(query)}&per_page=8`, { headers: { Authorization: API_KEY } })
        ]);

        const photos = (photoRes.status === 'fulfilled' ? photoRes.value.data.photos || [] : []).map((item: any) => ({
          id: `pexels-photo-${item.id}`,
          source: 'Pexels',
          title: item.alt || 'Pexels Photo',
          type: 'image',
          thumbnail: item.src.medium,
          downloadUrl: item.src.original,
          url: item.url
        }));

        const videos = (videoRes.status === 'fulfilled' ? videoRes.value.data.videos || [] : []).map((item: any) => ({
          id: `pexels-video-${item.id}`,
          source: 'Pexels',
          title: item.alt || 'Pexels Video',
          type: 'video',
          thumbnail: item.image,
          downloadUrl: item.video_files[0]?.link,
          url: item.url
        }));

        if (photos.length > 0 || videos.length > 0) return [...photos, ...videos];
      } else {
        const endpoint = type === 'video' ? 'videos/search' : 'search';
        const url = `https://api.pexels.com/v1/${endpoint}?query=${encodeURIComponent(query)}&per_page=12`;
        const response = await axiosInstance.get(url, { headers: { Authorization: API_KEY } });
        const items = type === 'video' ? response.data.videos : response.data.photos;
        
        return items.map((item: any) => ({
          id: `pexels-${type}-${item.id}`,
          source: 'Pexels',
          title: item.alt || `Pexels ${type}`,
          type: type === 'video' ? 'video' : 'image',
          thumbnail: type === 'video' ? item.image : item.src.medium,
          downloadUrl: type === 'video' ? item.video_files[0]?.link : item.src.original,
          url: item.url
        }));
      }
    } catch (err: any) {
      console.error('Pexels API Error:', err.message);
    }
  }

  try {
    const url = `https://www.pexels.com/search/${encodeURIComponent(query)}/`;
    const { data } = await axiosInstance.get(url);
    const $ = load(data);
    const results: any[] = [];
    
    $('article').each((i, el) => {
      if (i >= 20) return;
      const img = $(el).find('img').first();
      const src = img.attr('src') || img.attr('data-big-src');
      if (src) {
        results.push({
          id: `pexels-scrape-${i}`,
          source: 'Pexels',
          title: img.attr('alt') || 'Pexels Scraped',
          type: 'image',
          thumbnail: src,
          downloadUrl: src.split('?')[0],
        });
      }
    });
    if (results.length > 0) return results;
  } catch (err) {}

  // Workaround: Use Google to find Pexels images
  try {
    const url = `https://www.google.com/search?q=site:pexels.com+${encodeURIComponent(query)}&tbm=isch&safe=active`;
    const { data } = await axiosInstance.get(url);
    const $ = load(data);
    const results: any[] = [];

    $('img').each((i, el) => {
      const src = $(el).attr('src') || $(el).attr('data-src') || $(el).attr('data-iurl');
      if (src && (src.startsWith('http') || src.startsWith('data:image'))) {
        // Try to find the original pexels ID if possible from the alt or nearby text
        results.push({
          id: `pexels-google-${i}`,
          source: 'Pexels (via Google)',
          title: $(el).attr('alt') || 'Pexels Image',
          type: 'image',
          thumbnail: src,
          downloadUrl: src,
        });
      }
    });
    return results.filter(r => r.thumbnail.length > 50).slice(0, 30);
  } catch (err) {
    return [];
  }
}

async function searchPixabay(query: string, type: string) {
  const API_KEY = process.env.PIXABAY_API_KEY;
  if (API_KEY) {
    try {
      if (type === 'all') {
        const [photoRes, videoRes] = await Promise.all([
          axiosInstance.get(`https://pixabay.com/api/?key=${API_KEY}&q=${encodeURIComponent(query)}&per_page=15`),
          axiosInstance.get(`https://pixabay.com/api/videos/?key=${API_KEY}&q=${encodeURIComponent(query)}&per_page=15`)
        ]);

        const photos = (photoRes.data.hits || []).map((item: any) => ({
          id: `pixabay-photo-${item.id}`,
          source: 'Pixabay',
          title: item.tags || 'Pixabay Photo',
          type: 'image',
          thumbnail: item.webformatURL,
          downloadUrl: item.largeImageURL,
          url: item.pageURL
        }));

        const videos = (videoRes.data.hits || []).map((item: any) => ({
          id: `pixabay-video-${item.id}`,
          source: 'Pixabay',
          title: item.tags || 'Pixabay Video',
          type: 'video',
          thumbnail: item.videos.medium?.thumbnail || item.videos.tiny?.thumbnail,
          downloadUrl: item.videos.large?.url || item.videos.medium?.url,
          url: item.pageURL
        }));

        return [...photos, ...videos];
      } else {
        const endpoint = type === 'video' ? 'videos/' : '';
        const url = `https://pixabay.com/api/${endpoint}?key=${API_KEY}&q=${encodeURIComponent(query)}&per_page=30`;
        const response = await axiosInstance.get(url);
        
        return response.data.hits.map((item: any) => ({
          id: `pixabay-${type}-${item.id}`,
          source: 'Pixabay',
          title: item.tags || `Pixabay ${type}`,
          type: type === 'video' ? 'video' : 'image',
          thumbnail: type === 'video' ? (item.videos.medium?.thumbnail || item.videos.tiny?.thumbnail) : item.webformatURL,
          downloadUrl: type === 'video' ? (item.videos.large?.url || item.videos.medium?.url) : item.largeImageURL,
          url: item.pageURL
        }));
      }
    } catch (err: any) {
      console.error('Pixabay API Error:', err.message);
    }
  }

  try {
    const url = `https://pixabay.com/images/search/${encodeURIComponent(query)}/`;
    const { data } = await axiosInstance.get(url);
    const $ = load(data);
    const results: any[] = [];
    
    $('.container--37YpY img').each((i, el) => {
      if (i >= 20) return;
      const src = $(el).attr('src') || $(el).attr('data-lazy');
      if (src && src.includes('http')) {
        results.push({
          id: `pixabay-scrape-${i}`,
          source: 'Pixabay',
          title: $(el).attr('alt') || 'Pixabay Scraped',
          type: 'image',
          thumbnail: src,
          downloadUrl: src.replace('_340.', '_1280.'),
        });
      }
    });
    return results;
  } catch (err) {
    return [];
  }
}

async function searchGoogle(query: string, type: string) {
  try {
    const url = `https://www.google.com/search?q=${encodeURIComponent(query)}&tbm=isch&safe=active&nfpr=1`;
    const { data } = await axiosInstance.get(url);
    const $ = load(data);
    const results: any[] = [];
    
    $('img').each((i, el) => {
      const src = $(el).attr('src') || $(el).attr('data-src') || $(el).attr('data-iurl');
      if (src && (src.startsWith('http') || src.startsWith('data:image'))) {
        results.push({
          id: `google-scrape-${i}-${Math.random().toString(36).substr(2, 5)}`,
          source: 'Google',
          title: $(el).attr('alt') || `Google Result ${i}`,
          type: 'image',
          thumbnail: src,
          downloadUrl: src,
        });
      }
    });

    if (results.length < 5) {
      try {
        const ddgUrl = `https://duckduckgo.com/html/?q=${encodeURIComponent(query)}+images`;
        const { data: ddgData } = await axiosInstance.get(ddgUrl);
        const $$ = load(ddgData);
        $$('img').each((i, el) => {
          const src = $$(el).attr('src');
          if (src && src.includes('http')) {
            results.push({
              id: `ddg-scrape-${i}`,
              source: 'Google (via Fallback)',
              title: $$(el).attr('alt') || 'Web Image',
              type: 'image',
              thumbnail: src,
              downloadUrl: src,
            });
          }
        });
      } catch (e) {}
    }

    return results.filter(r => r.thumbnail && r.thumbnail.length > 50).slice(0, 30); 
  } catch (err: any) {
    console.error('Google search failed:', err.message);
    return [];
  }
}
