import { NextRequest, NextResponse } from 'next/server';
import axios from 'axios';
import { load } from 'cheerio';
import { ResultItem } from '@/types';
import { canAutoUseMedia, withMediaRights } from '@/lib/mediaRights';
import { primaryAssetKey } from '@/lib/mediaIdentity';
import { isVisuallyUnsafeForScene } from '@/lib/mediaSafety';

const cache = new Map<string, { data: ResultItem[], timestamp: number }>();
const CACHE_TTL = 1000 * 60 * 10; // 10 minutes
const AI_GENERATED_PATTERN = /\b(ai[- ]generated|generative ai|generated by ai|midjourney|stable diffusion|dall[- ]?e)\b/i;
const GENERATED_STYLE_PATTERN = /\b(ai|artificial intelligence|render|rendered|3d|cgi|fantasy|illustration|illustrated|illus\.|digital art|concept art|vector|clipart|clip art|cartoon|anime|drawing|sketch|watercolor|icon|icons|symbol|sticker|logo|isolated|transparent|svg|mockup|template|abstract|graphic|isometric|cutout|decorative)\b/i;
const GENERATED_SOURCE_PATTERN = /\bgoogle|fallback|scrape\b/i;
const BLOCKED_STOCK_OR_SLIDE_PATTERN = /\b(adobe\s*stock|adobestock|stock\.adobe|alamy|shutterstock|getty|istock|dreamstime|depositphotos|123rf|freepik|vecteezy|envato|stock\s*photo|stock-photo|stock\s*image|royalty[-\s]*free|watermark|watermarked|slideplayer|timetoast|pinterest|slideshare)\b/i;
const NON_VISUAL_PAGE_PATTERN = /\b(category:|category page|wikimedia commons category|mediawiki|search results|free encyclopedia)\b/i;
const NON_VISUAL_URL_PATTERN = /\/wiki\/Category:|commons\.wikimedia\.org\/wiki\/Category:/i;
const WEB_IMAGE_SOURCES = ['DuckDuckGo', 'Bing', 'Yahoo'];

interface DuckDuckGoImage {
  image?: string;
  thumbnail?: string;
  title?: string;
  url?: string;
}

interface BingImageMetadata {
  mid?: string;
  md5?: string;
  t?: string;
  murl?: string;
  turl?: string;
  purl?: string;
  desc?: string;
}

type CaseTimePreference = 'unspecified' | 'day' | 'night';

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}

function isResultItem(item: ResultItem | null): item is ResultItem {
  return Boolean(item);
}

function isAiGeneratedStockResult(item: {
  source?: string;
  title?: string;
  description?: string;
  tags?: string[];
  thumbnail?: string;
  downloadUrl?: string;
  url?: string;
}) {
  if (GENERATED_SOURCE_PATTERN.test(item.source || '')) return true;
  const searchableText = [
    item.title || '',
    item.description || '',
    ...(item.tags || []),
  ].join(' ');
  const mediaUrls = `${item.thumbnail || ''} ${item.downloadUrl || ''} ${item.url || ''}`;
  return AI_GENERATED_PATTERN.test(searchableText)
    || GENERATED_STYLE_PATTERN.test(searchableText)
    || NON_VISUAL_PAGE_PATTERN.test(searchableText)
    || BLOCKED_STOCK_OR_SLIDE_PATTERN.test(searchableText)
    || BLOCKED_STOCK_OR_SLIDE_PATTERN.test(mediaUrls)
    || NON_VISUAL_URL_PATTERN.test(mediaUrls)
    || GENERATED_STYLE_PATTERN.test(mediaUrls)
    || /\.svg(?:\?|$)/i.test(mediaUrls);
}

function normalizeCaseTitle(value: string) {
  return value.replace(/\s+/g, ' ').trim();
}

function normalizeCaseTimePreference(value: unknown): CaseTimePreference {
  if (typeof value !== 'string') return 'unspecified';
  const key = value.toLowerCase();
  if (key.includes('night')) return 'night';
  if (key.includes('day')) return 'day';
  return 'unspecified';
}

function withTrueCrimeCaseTitle(query: string, niche: string, caseTitle: string) {
  const cleanQuery = query.replace(/\s+/g, ' ').trim();
  const cleanCase = normalizeCaseTitle(caseTitle);
  if (!cleanQuery || !cleanCase || !niche.toLowerCase().includes('true crime')) return cleanQuery;
  if (cleanQuery.toLowerCase().includes(cleanCase.toLowerCase())) return cleanQuery;
  return `${cleanCase} ${cleanQuery}`;
}

function withTrueCrimeCaseTime(query: string, niche: string, caseTime: CaseTimePreference) {
  const cleanQuery = query.replace(/\s+/g, ' ').trim();
  if (!cleanQuery || !niche.toLowerCase().includes('true crime') || caseTime === 'unspecified') return cleanQuery;
  const lower = cleanQuery.toLowerCase();
  if (/\b(court|courtroom|trial|mugshot|records?|documents?|newspaper|poster|report|file|map|timeline)\b/i.test(lower)) {
    return cleanQuery;
  }
  if (caseTime === 'night') {
    return /\b(night|nighttime|midnight|evening|after dark|dark)\b/i.test(lower)
      ? cleanQuery
      : `${cleanQuery} night`;
  }
  return /\b(daytime|daylight|morning|afternoon|sunny|day scene)\b/i.test(lower)
    ? cleanQuery
    : `${cleanQuery} daylight`;
}

function nicheSearchQuery(query: string, niche: string, era: string, caseTitle = '', caseTime: CaseTimePreference = 'unspecified') {
  const anchoredQuery = withTrueCrimeCaseTime(withTrueCrimeCaseTitle(query, niche, caseTitle), niche, caseTime);
  const clean = [anchoredQuery, era].filter(Boolean).join(' ').replace(/\s+/g, ' ').trim();
  const key = niche.toLowerCase();
  if (!key) return clean;
  if (key.includes('history')) return `${clean} vintage archival documentary photo old film still newsreel`;
  if (key.includes('true crime')) return `${clean} true crime real case photo evidence`;
  if (key.includes('motivational')) return `${clean} cinematic real photo people action`;
  if (key.includes('self improvement')) return `${clean} habits routine focus real photo`;
  if (key.includes('finance')) return `${clean} finance money banking real photo`;
  return `${clean} real photo`;
}

// Configure axios default timeout
const axiosInstance = axios.create({
  timeout: 10000, // 10 seconds timeout
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
  }
});

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const query = searchParams.get('q');
    const type = searchParams.get('type') || 'all';
    const era = searchParams.get('era') || '';
    const providers = searchParams.get('providers') || 'all';
    const niche = searchParams.get('niche') || '';
    const caseTitle = searchParams.get('caseTitle') || '';
    const caseTime = normalizeCaseTimePreference(searchParams.get('caseTime'));
    const rightsMode = searchParams.get('rights') === 'unfiltered' ? 'unfiltered' : 'filtered';
    const unfilteredWeb = rightsMode === 'unfiltered';

    if (!query) {
      return NextResponse.json({ error: 'Query is required' }, { status: 400 });
    }

    const searchQuery = nicheSearchQuery(query, niche, era, caseTitle, caseTime);
    const cacheKey = `web-image-v19-${searchQuery}-${type}-${era}-${providers}-${niche}-${caseTitle}-${caseTime}-${rightsMode}`;
    const cached = cache.get(cacheKey);
    if (cached && (Date.now() - cached.timestamp < CACHE_TTL)) {
      return NextResponse.json({ results: cached.data, cached: true });
    }

    const providersToSearch = [
      searchDuckDuckGoImages(searchQuery, rightsMode),
      searchBingImages(searchQuery, rightsMode),
      searchYahooImages(searchQuery, rightsMode),
    ];
    const results = await Promise.allSettled(providersToSearch);

    const flatResults = results.flatMap((result) => (
      result.status === 'fulfilled' ? result.value : []
    ));
    const visibleResults = flatResults
      .filter((item) => !isAiGeneratedStockResult(item))
      .filter((item) => !isVisuallyUnsafeForScene(item, { query: searchQuery, niche }))
      .map((item) => withMediaRights(item as ResultItem, {
        providerFiltered: !unfilteredWeb && WEB_IMAGE_SOURCES.includes(item.source),
        allowUnfilteredWeb: unfilteredWeb,
      }))
      .filter(canAutoUseMedia);
    const dedupedResults = Array.from(new Map(
      visibleResults.map((item) => [primaryAssetKey(item), item]),
    ).values()).sort((left, right) => (
      searchRelevanceScore(right, searchQuery, niche, caseTitle, caseTime)
      - searchRelevanceScore(left, searchQuery, niche, caseTitle, caseTime)
    ));

    // Save to cache
    cache.set(cacheKey, { data: dedupedResults, timestamp: Date.now() });

    return NextResponse.json({ results: dedupedResults });
  } catch (error: unknown) {
    console.error('Search API Error:', error);
    return NextResponse.json({ 
      error: 'Search failed', 
      details: getErrorMessage(error),
    }, { status: 500 });
  }
}

function normalizeImageUrl(value: unknown) {
  if (typeof value !== 'string') return '';
  const trimmed = value.trim();
  if (!/^https?:\/\//i.test(trimmed)) return '';
  if (/\.svg(?:\?|$)/i.test(trimmed)) return '';
  return trimmed;
}

function imageResult({
  id,
  source,
  title,
  image,
  thumbnail,
  pageUrl,
  description = '',
  tags = [],
}: {
  id: string;
  source: string;
  title: string;
  image: string;
  thumbnail?: string;
  pageUrl?: string;
  description?: string;
  tags?: string[];
}): ResultItem | null {
  const downloadUrl = normalizeImageUrl(image);
  const preview = normalizeImageUrl(thumbnail) || downloadUrl;
  if (!downloadUrl || !preview) return null;
  return {
    id,
    source,
    title: title || `${source} image`,
    type: 'image',
    thumbnail: preview,
    downloadUrl,
    url: pageUrl,
    description,
    downloads: 0,
    tags,
  };
}

const SEARCH_RANK_STOP_WORDS = new Set([
  'the', 'and', 'for', 'with', 'from', 'into', 'that', 'this', 'real', 'case',
  'photo', 'image', 'evidence', 'true', 'crime', 'documentary', 'photos',
  'picture', 'pictures', 'scene',
]);
const TRUE_CRIME_LOCATION_ANCHOR_TERMS = new Set([
  'road', 'street', 'forest', 'woods', 'trail', 'mountain', 'snow', 'snowy',
  'cabin', 'house', 'home', 'vehicle', 'car', 'highway', 'plumas', 'national',
  'dirt', 'dark', 'midnight', 'night',
]);

function meaningfulSearchTerms(value: string) {
  return Array.from(new Set(
    (value.toLowerCase().match(/[a-z0-9][a-z0-9'-]{2,}/g) || [])
      .filter((term) => !SEARCH_RANK_STOP_WORDS.has(term)),
  ));
}

function resultActualText(item: ResultItem) {
  return [
    item.title,
    item.description || '',
    item.url || '',
    item.sourcePageUrl || '',
    item.downloadUrl || '',
  ].join(' ').toLowerCase();
}

function isTrueCrimeLocationQuery(value: string) {
  return /\b(road|street|forest|woods?|trail|mountain|snow|cabin|house|home|vehicle|car|scene|location|area|highway|bridge|river|lake|field|parking|driveway|store|motel|hotel|apartment)\b/i.test(value)
    && !/\b(court|courtroom|trial|mugshot|records?|documents?|newspaper|poster|report|file|map|timeline|article)\b/i.test(value);
}

function hasNightSignal(value: string) {
  return /\b(night|nighttime|midnight|evening|after dark|dark road|dark street|dark forest|dark woods|dark highway|dark mountain|dark cabin|eerie midnight|headlights?)\b/i.test(value);
}

function hasDaySignal(value: string) {
  return /\b(daylight|daytime|sunny|morning|afternoon|blue sky|day road|day forest|daytime forest)\b/i.test(value);
}

function searchRelevanceScore(item: ResultItem, query: string, niche: string, caseTitle: string, caseTime: CaseTimePreference) {
  const actualText = resultActualText(item);
  const queryTerms = meaningfulSearchTerms(query);
  const visualAnchorTerms = queryTerms.filter((term) => TRUE_CRIME_LOCATION_ANCHOR_TERMS.has(term));
  const caseTerms = meaningfulSearchTerms(caseTitle);
  let score = 0;
  score += queryTerms.filter((term) => actualText.includes(term)).length * 6;
  score += caseTerms.filter((term) => actualText.includes(term)).length * 10;
  if (caseTitle && actualText.includes(caseTitle.toLowerCase())) score += 35;
  if (niche.toLowerCase().includes('true crime')) {
    const timeSensitive = isTrueCrimeLocationQuery(query);
    if (timeSensitive) {
      score += visualAnchorTerms.filter((term) => actualText.includes(term)).length * 14;
    }
    if (caseTime === 'night') {
      if (hasNightSignal(actualText)) score += timeSensitive ? 45 : 18;
      if (hasDaySignal(actualText)) score -= timeSensitive ? 35 : 10;
      if (timeSensitive && !hasNightSignal(actualText)) score -= 25;
    }
    if (caseTime === 'day') {
      if (hasDaySignal(actualText)) score += timeSensitive ? 35 : 18;
      if (hasNightSignal(actualText)) score -= timeSensitive ? 30 : 10;
    }
    if (caseTitle && caseTerms.length > 0 && caseTerms.every((term) => !actualText.includes(term))) score -= 18;
    if (/\b(police line|police tape|crime scene tape)\b/.test(actualText) && !/\b(police line|police tape|crime scene tape)\b/.test(query.toLowerCase())) {
      score -= 16;
    }
  }
  if (BLOCKED_STOCK_OR_SLIDE_PATTERN.test(actualText)) score -= 100;
  return score;
}

async function getDuckDuckGoVqd(query: string) {
  const response = await axiosInstance.get(`https://duckduckgo.com/?q=${encodeURIComponent(query)}&iax=images&ia=images`);
  const text = String(response.data || '');
  return text.match(/vqd=['"]?([^'"\s&]+)['"]?/)?.[1] || '';
}

async function searchDuckDuckGoImages(query: string, rightsMode: 'filtered' | 'unfiltered'): Promise<ResultItem[]> {
  try {
    const vqd = await getDuckDuckGoVqd(query);
    if (!vqd) return [];
    const response = await axiosInstance.get('https://duckduckgo.com/i.js', {
      params: {
        l: 'us-en',
        o: 'json',
        q: query,
        vqd,
        ...(rightsMode === 'filtered' ? { f: ',,,,,license:ModifyCommercially' } : {}),
        p: '1',
      },
      headers: {
        Referer: `https://duckduckgo.com/?q=${encodeURIComponent(query)}&iax=images&ia=images`,
      },
    });
    const results = Array.isArray(response.data?.results) ? response.data.results as DuckDuckGoImage[] : [];
    return results.slice(0, 18).map((item, index) => imageResult({
      id: `ddg-${Buffer.from(`${item.image || item.thumbnail || index}`).toString('base64url').slice(0, 24)}`,
      source: 'DuckDuckGo',
      title: item.title || query,
      image: item.image || '',
      thumbnail: item.thumbnail,
      pageUrl: item.url,
      description: item.title || '',
    })).filter(isResultItem);
  } catch (err: unknown) {
    console.error('DuckDuckGo image search failed:', getErrorMessage(err));
    return [];
  }
}

async function searchBingImages(query: string, rightsMode: 'filtered' | 'unfiltered'): Promise<ResultItem[]> {
  const url = 'https://www.bing.com/images/search';
  try {
    const response = await axiosInstance.get(url, {
      params: {
        q: query,
        safeSearch: 'Strict',
        ...(rightsMode === 'filtered' ? {
          qft: '+filterui:license-L2_L3_L4',
          form: 'IRFLTR',
        } : {}),
      },
      headers: { Referer: 'https://www.bing.com/' },
    });
    const $ = load(response.data);
    const results: ResultItem[] = [];
    $('a.iusc').each((index, element) => {
      const raw = $(element).attr('m');
      if (!raw) return;
      try {
        const metadata = JSON.parse(raw.replace(/&quot;/g, '"')) as BingImageMetadata;
        const result = imageResult({
          id: `bing-${metadata.mid || metadata.md5 || index}`,
          source: 'Bing',
          title: metadata.t || query,
          image: metadata.murl || '',
          thumbnail: metadata.turl,
          pageUrl: metadata.purl,
          description: metadata.desc || metadata.t || '',
        });
        if (result) results.push(result);
      } catch {}
    });
    return results.slice(0, 18);
  } catch (err: unknown) {
    console.error('Bing image search failed:', getErrorMessage(err));
    return [];
  }
}

async function searchYahooImages(query: string, rightsMode: 'filtered' | 'unfiltered'): Promise<ResultItem[]> {
  try {
    const response = await axiosInstance.get('https://images.search.yahoo.com/search/images', {
      params: {
        p: query,
        vm: 'r',
        ...(rightsMode === 'filtered' ? { imgl: 'fsu' } : {}),
      },
      headers: { Referer: 'https://images.search.yahoo.com/' },
    });
    const html = String(response.data || '');
    const $ = load(html);
    const results: ResultItem[] = [];
    $('img').each((index, element) => {
      const image = $(element).attr('data-src') || $(element).attr('src') || '';
      const result = imageResult({
        id: `yahoo-img-${index}-${Buffer.from(image).toString('base64url').slice(0, 12)}`,
        source: 'Yahoo',
        title: $(element).attr('alt') || query,
        image,
        thumbnail: image,
        pageUrl: undefined,
        description: $(element).attr('alt') || '',
      });
      if (result) results.push(result);
    });
    const jsonImageMatches = Array.from(html.matchAll(/"iurl":"([^"]+)"/g));
    jsonImageMatches.slice(0, 18).forEach((match, index) => {
      const image = match[1].replace(/\\u002F/g, '/').replace(/\\/g, '');
      const result = imageResult({
        id: `yahoo-json-${index}-${Buffer.from(image).toString('base64url').slice(0, 12)}`,
        source: 'Yahoo',
        title: query,
        image,
        thumbnail: image,
      });
      if (result) results.push(result);
    });
    const unique = new Map(results.map((result) => [result.downloadUrl, result]));
    return Array.from(unique.values()).slice(0, 18);
  } catch (err: unknown) {
    console.error('Yahoo image search failed:', getErrorMessage(err));
    return [];
  }
}
